language: node_js
node_js:
- stable
script:
- npm test
addons:
  browserstack:
    username: jjjpanda1
    access_key:
      secure: vt998LFvTyyZ/Oz/I8debCvgTSFrEq+n+4kJZVZajs/w/NomKP9O/qlHHKFzdIGxV3Y/5BvVYGVM0+27iGUKMoZR1K7ZLmxlwse49wQicvvs38auO5fd7ueTB8GzLQs+4an0WzXedgkYrCJoqvOqLj4imqTPUFwfICVFJaAHzECaN2Rlntj5+T/TVNcdtg43x3sFlCWTdduB+psRcYAew1Hr84Bs/NWHIXylOlI72wFTNtd08PjW2NxHV59EQZj7+4GITC9s63PoNHnDPybn8y+vnI/6e/RSXrjY65M4INQbKbQhEgfpW3d6j0hMX5nQxOKwq4CdGlowhutDYlT7bjGaX2fviyzREE3yuuuCfiBcXsnw3JTKO4BRAxpqJ+/Rgn3bDvMPI6Tqxlr93cv/YV3YFJsQ8BqXizDq8jKOA7OPl/KYE1RyrRWPPvxjxCEB3UTivEZVY5KpqoBr1x+yduU7Rdae2KPSpDeTRrCT+MBgtYwMKy3Smqq0kRAJnl8FCT3PSNednPYbXHsl8Ea5RMgNNyL7VUV74w2NxhkwNkAv6DeOXpN7DdYl3RK5+xq4l94ZdaMqvY+WkQJSpTI+ST5OsdhAZr6Zw2vEYPyJY7S0FwrJN4zHsQKHK2Au7UCHBpSWA+BiDNNTjCvXCbxbNdpIFLLt5k3Nx93PAgxSiuo=
env:
  global:
  - secure: e4c1q8o/kfHsP/BCyE/i1e7vEcZWXiIPRfEsQwAWRa9KZWO5V2EdAx4AbAHk+IAdXlzssjgN6LYl8KcDGhVn88NT3TFH+HXWmTYD1CLgbJdHwMo1cfjak9X/uuI+RBi65RHXWrdcy5CoYAQ5ufN4/s/FPocdYFHmQW8fCN4xGNjK48GuzXl67mLlEommHKDZw3Gv/zGGOkmOe5nXxTaRmhc2bPk0qSA73WuvNXx5L49jD87++E1blO/2vnVo1VfZaDoDRzyb8t6I1uMPkaW0RPK8dRD9Jrip4Pvj9dl1XbOeJWmpLJygfjRgcGXz5E+pSa+5OFUH1PfvCrntLj8WHfiIHvfB0+CSyGr3LEJ72Ke4X6GRDWCMra8zM3mi1sw5fw+V+aVcIS5YggUoIrJf7KjLbzuEPw74rw7VA1FnglNSmkZx5gw2WsYVnGZMwuqBGamN+SPa9vpnfWlIOaWKNhaug5QoafAXyVZ8aPSkdX6D1xnn2vmoRNarKcfN6qs/4m9xM9bK6sj6SYSYOVuBHJUv4/pf878xJTbwuD8/xC7cwtB/tyOF556PTHi5h3gNN46Axa4h2iULGh3tAMbPCj+nEM/diq0Vwugc0HSJI2upgAxxq8lG1G+OjIb25TZ0kpKeQgF7QZCTDrhfkKbwq04LLZxMWUaxr793y94jyv8=
